# Generated by Django 3.1.7 on 2021-03-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eReservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='num_of_chairs',
            new_name='seats',
        ),
    ]
