# Generated by Django 3.1.7 on 2021-03-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eReservation', '0002_auto_20210309_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'from_hour']},
        ),
    ]
