# Generated by Django 3.1.7 on 2021-03-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ['day_of_the_week']},
        ),
        migrations.AlterField(
            model_name='dish',
            name='mod_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mod_date',
            field=models.DateField(auto_now=True),
        ),
    ]
