# Generated by Django 3.1.7 on 2021-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0003_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
